// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuUUmR-P7gW2_A7hOXrDu80V4bJYIExFo',
    appId: '1:1069372312379:android:68c3520080cd5f4d33851e',
    messagingSenderId: '1069372312379',
    projectId: 'two-minutes-b2438',
    storageBucket: 'two-minutes-b2438.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYGjZL2qiQwK9tfXX5RJeesmQdjjNKpYc',
    appId: '1:1069372312379:ios:193fc18bf2b775d533851e',
    messagingSenderId: '1069372312379',
    projectId: 'two-minutes-b2438',
    storageBucket: 'two-minutes-b2438.firebasestorage.app',
    iosClientId: '1069372312379-cqrrtp5liiesauj817r59oiootdnrnsn.apps.googleusercontent.com',
    iosBundleId: 'com.yanazhd.twoMins',
  );
}
